import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { db } from "@/db";
import { users } from "@/db/schema";

/**
 * POST /api/reports/export/pdf
 * Generate laporan PDF dengan metrik per staff.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const period = body.period || "bulanan";
    const username = body.username || "all";
    const sprint = body.sprint || "all";
    const periodLabel = period === "kuartalan" ? "Kuartalan" : "Bulanan";

    // Fetch staff metrics from the reports API
    const baseUrl = request.nextUrl.origin;
    const res = await fetch(`${baseUrl}/api/reports?period=${period}&username=${username}&sprint=${sprint}`);
    const data = await res.json();

    // Create PDF
    const doc = new jsPDF("landscape");
    const now = new Date().toLocaleDateString("id-ID", { year: "numeric", month: "long", day: "numeric" });

    // Cover
    doc.setFontSize(22);
    doc.text("TaskFlow Pro — Laporan Kinerja Eksekutif", 14, 20);
    doc.setFontSize(11);
    doc.text(`Periode: ${periodLabel}  |  Tanggal: ${now}  |  Filter Sprint: ${sprint}  |  User: ${username}`, 14, 28);

    // Summary Cards Text
    doc.setFontSize(10);
    doc.text(
      `Rata-rata Skor: ${data.summary?.avgPerformanceScore || 0}/100   |   Total Tugas: ${data.summary?.totalTasks || 0} (${data.summary?.doneTasks || 0} Selesai - ${data.summary?.completionRate || 0}%)   |   Total Workload: ${data.summary?.totalWorkload || 0}j / ${data.summary?.totalCapacity || 0}j`,
      14,
      36
    );

    // Staff table
    if (data.staff?.length > 0) {
      autoTable(doc, {
        startY: 42,
        head: [["Nama", "Role", "Kapasitas", "Beban", "Utilisasi", "Subtasks", "Review Lead", "Skor", "Kategori"]],
        body: data.staff.map((s: any) => [
          s.name,
          (s.role || "staff").toUpperCase(),
          `${s.capacity}j`,
          `${s.workload}j`,
          `${s.utilization}%`,
          `${s.subtasksDone}/${s.subtasksTotal}`,
          s.role === "lead" ? `${s.reviewsDone}/${s.reviewsTotal}` : "-",
          `${s.performanceScore || 0}/100`,
          s.performanceCategory || (s.isOverload ? "Overload" : "Optimal"),
        ]),
        didDrawCell: (hookData) => {
          // Highlight overload rows
          if (hookData.row.section === "body" && hookData.column.index === 5 && hookData.cell.raw === "OVERLOAD") {
            (hookData.cell as any).styles = { textColor: [220, 38, 38], fontStyle: "bold" };
          }
        },
      });
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Halaman ${i} dari ${pageCount} — Generated by TaskFlow Pro — ${now}`, 20, 287);
    }

    const pdfBytes = doc.output("arraybuffer");
    return new NextResponse(pdfBytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="laporan-taskflow-${period}.pdf"`,
      },
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
